# Generated by Django 5.1 on 2024-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup', models.CharField(help_text='Question to set up a joke', max_length=255)),
                ('punchline', models.CharField(help_text='Answer to resolve the joke', max_length=255)),
            ],
        ),
    ]
