# Generated by Django 5.1 on 2024-09-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_joke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joke',
        ),
    ]
